# Generated by Django 4.1 on 2022-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('synopsis', models.TextField(blank=True, max_length=1000)),
                ('genre', models.CharField(choices=[('AC', 'Accion'), ('DR', 'Drama'), ('COMEDY', 'Comedy'), ('SF', 'Ciencia Ficcion'), ('TR', 'Triler'), ('RG', 'Religioso')], default='', max_length=100)),
            ],
        ),
    ]
