# Generated by Django 4.1 on 2022-08-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('AC', 'Accion'), ('DR', 'Drama'), ('CM', 'Comedy'), ('SF', 'Ciencia Ficcion'), ('TR', 'Triler'), ('RG', 'Religioso')], default='', max_length=100),
        ),
    ]
