# Generated by Django 4.1 on 2022-08-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.JSONField(default=[]),
        ),
    ]
