# Generated by Django 4.1 on 2022-08-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tag',
            field=models.JSONField(default=dict),
        ),
    ]
